version: "3.9"
services:
  database_8:
    image: mysql:latest
    container_name: quiz-mysql-database-8
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_quiz_password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-database_quiz}
      MYSQL_USER: ${MYSQL_USER:-quiz_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-quiz_password}
    networks:
      - development_network

volumes:
  db_data:

networks:
  development_network: